modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "genesis"
version = "${version}"
displayName = "Genesis"
authors = "G_Mungus, Quoissant, Cosmos, Frisk256, Acrogenous, BrickyBoy, Jcm, metafive, GuyApooye, ThePlasticPotato"
description = '''
A space mod for Valkyrien Skies.
'''
logoFile = "assets/genesis/icon.png"

[[dependencies.genesis]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.genesis]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.genesis]]
modId = "vlib"
mandatory = true
versionRange = "[1.20.1-0.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.genesis]]
modId = "zps"
mandatory = true
versionRange = "[1.20.1-2.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.genesis]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.4.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.genesis]]
modId = "lodestone"
mandatory = true
versionRange = "[1.20.1-1.6.4,)"
ordering = "NONE"
side = "CLIENT"
