modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="cosmos"
version="0.0.7.3"
displayName="Cosmic Horizons"
displayURL="https://cosmic-mod.github.io/"
logoFile="logo.png"
credits="created by Death"
authors="DEA__TH"
description="A space mod never seen before!!!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.cosmos]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.cosmos]]
    modId="particlepresets"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration