package net.lointain.cosmos.init;

import net.lointain.cosmos.block.AmmoniaBlock;
import net.lointain.cosmos.block.ArgonBlock;
import net.lointain.cosmos.block.AshedSulpherStoneBlock;
import net.lointain.cosmos.block.AshedsulphuricTntBlock;
import net.lointain.cosmos.block.BoronBlock;
import net.lointain.cosmos.block.BrightFireBlock;
import net.lointain.cosmos.block.CableNBlock;
import net.lointain.cosmos.block.CableeBlock;
import net.lointain.cosmos.block.CablefBlock;
import net.lointain.cosmos.block.CableiBlock;
import net.lointain.cosmos.block.CablelBlock;
import net.lointain.cosmos.block.CablelcBlock;
import net.lointain.cosmos.block.CablelccBlock;
import net.lointain.cosmos.block.CableltBlock;
import net.lointain.cosmos.block.CableltcBlock;
import net.lointain.cosmos.block.CablesBlock;
import net.lointain.cosmos.block.CabletBlock;
import net.lointain.cosmos.block.CabletcBlock;
import net.lointain.cosmos.block.CabletxBlock;
import net.lointain.cosmos.block.CabletxcBlock;
import net.lointain.cosmos.block.CabletxccBlock;
import net.lointain.cosmos.block.CablexBlock;
import net.lointain.cosmos.block.CablexcBlock;
import net.lointain.cosmos.block.ChamberedSuperSmelterblockBlock;
import net.lointain.cosmos.block.ChiseledMartianStoneBlock;
import net.lointain.cosmos.block.CompressedFrozenMoonClaydustBlock;
import net.lointain.cosmos.block.CompressedStoneBlock;
import net.lointain.cosmos.block.ConcentratedsulpheroreBlock;
import net.lointain.cosmos.block.CorrodedSulpherTNTBlock;
import net.lointain.cosmos.block.CrudeOilBlock;
import net.lointain.cosmos.block.DetonatorTargetBlock;
import net.lointain.cosmos.block.DetonatorTargetOnBlock;
import net.lointain.cosmos.block.ExtinguishedLanternBlock;
import net.lointain.cosmos.block.ExtinguishedLanternHangingBlock;
import net.lointain.cosmos.block.ExtinguishedtorchBlock;
import net.lointain.cosmos.block.ExtinguishedtorchwallBlock;
import net.lointain.cosmos.block.FlourineBlock;
import net.lointain.cosmos.block.FrozenTitaniumoreBlock;
import net.lointain.cosmos.block.HeightLimiterBlock;
import net.lointain.cosmos.block.HeliumBlock;
import net.lointain.cosmos.block.HighlyCompressedIceBlock;
import net.lointain.cosmos.block.HydrogenBlock;
import net.lointain.cosmos.block.LargesolarpanelBlock;
import net.lointain.cosmos.block.MartianStoneBricksBlock;
import net.lointain.cosmos.block.MartianStoneTilesBlock;
import net.lointain.cosmos.block.MatianSandBlock;
import net.lointain.cosmos.block.MethaneBlock;
import net.lointain.cosmos.block.MoonClaydustBlock;
import net.lointain.cosmos.block.NickleBlockBlock;
import net.lointain.cosmos.block.Nicklespaceship2Block;
import net.lointain.cosmos.block.Nicklespaceship3Block;
import net.lointain.cosmos.block.Nicklespaceship4Block;
import net.lointain.cosmos.block.NicklespaceshipBlock;
import net.lointain.cosmos.block.Nicklespaceshipupright2Block;
import net.lointain.cosmos.block.Nicklespaceshipupright3Block;
import net.lointain.cosmos.block.Nicklespaceshipupright4Block;
import net.lointain.cosmos.block.NicklespaceshipuprightBlock;
import net.lointain.cosmos.block.NitrogenBlock;
import net.lointain.cosmos.block.PolishedMartianStoneBlock;
import net.lointain.cosmos.block.ProjectorTableBlock;
import net.lointain.cosmos.block.RawNickelStoneBlock;
import net.lointain.cosmos.block.SiliconedmoonclayBlock;
import net.lointain.cosmos.block.SmallsolarpanelBlock;
import net.lointain.cosmos.block.SteelBatteryBlock;
import net.lointain.cosmos.block.SteelBlockBlock;
import net.lointain.cosmos.block.SteelLandingPadOFFBlock;
import net.lointain.cosmos.block.SteelLandingPadONBlock;
import net.lointain.cosmos.block.SteelRestoneRecieverOFFBlock;
import net.lointain.cosmos.block.SteelRestoneRecieverONBlock;
import net.lointain.cosmos.block.SteelSpaceshipuprightBlock;
import net.lointain.cosmos.block.Steelbatter1Block;
import net.lointain.cosmos.block.Steelbatter2Block;
import net.lointain.cosmos.block.Steelbatter3Block;
import net.lointain.cosmos.block.Steelbatter4Block;
import net.lointain.cosmos.block.Steelspaceship2Block;
import net.lointain.cosmos.block.Steelspaceship3Block;
import net.lointain.cosmos.block.Steelspaceship4Block;
import net.lointain.cosmos.block.SteelspaceshipBlock;
import net.lointain.cosmos.block.Steelspaceshipupright2Block;
import net.lointain.cosmos.block.Steelspaceshipupright3Block;
import net.lointain.cosmos.block.Steelspaceshipupright4Block;
import net.lointain.cosmos.block.StonecoreblockBlock;
import net.lointain.cosmos.block.SulpherStoneBlock;
import net.lointain.cosmos.block.SulphuricAcidBlock;
import net.lointain.cosmos.block.SulphuricSandBlock;
import net.lointain.cosmos.block.TitaniumBlockBlock;
import net.lointain.cosmos.block.TitaniumSpaceshipuprightBlock;
import net.lointain.cosmos.block.Titaniumspaceship2Block;
import net.lointain.cosmos.block.Titaniumspaceship3Block;
import net.lointain.cosmos.block.Titaniumspaceship4Block;
import net.lointain.cosmos.block.TitaniumspaceshipBlock;
import net.lointain.cosmos.block.Titaniumspaceshipupright2Block;
import net.lointain.cosmos.block.Titaniumspaceshipupright3Block;
import net.lointain.cosmos.block.Titaniumspaceshipupright4Block;
import net.lointain.cosmos.block.VapourBlock;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class CosmosModBlocks {
   public static final DeferredRegister<Block> REGISTRY;
   public static final RegistryObject<Block> MOON_CLAYDUST;
   public static final RegistryObject<Block> HIGHLY_COMPRESSED_ICE;
   public static final RegistryObject<Block> COMPRESSED_FROZEN_MOON_CLAYDUST;
   public static final RegistryObject<Block> SULPHURIC_SAND;
   public static final RegistryObject<Block> CONCENTRATEDSULPHERORE;
   public static final RegistryObject<Block> SULPHER_STONE;
   public static final RegistryObject<Block> FROZEN_TITANIUMORE;
   public static final RegistryObject<Block> TITANIUM_BLOCK;
   public static final RegistryObject<Block> SILICONEDMOONCLAY;
   public static final RegistryObject<Block> CHAMBERED_SUPER_SMELTERBLOCK;
   public static final RegistryObject<Block> BRIGHT_FIRE;
   public static final RegistryObject<Block> SULPHER_TNT;
   public static final RegistryObject<Block> ASHEDSULPHURIC_TNT;
   public static final RegistryObject<Block> HEIGHT_LIMITER;
   public static final RegistryObject<Block> LARGESOLARPANEL;
   public static final RegistryObject<Block> SMALLSOLARPANEL;
   public static final RegistryObject<Block> CABLEE;
   public static final RegistryObject<Block> CABLE_N;
   public static final RegistryObject<Block> CABLES;
   public static final RegistryObject<Block> CABLEI;
   public static final RegistryObject<Block> CABLEL;
   public static final RegistryObject<Block> CABLELC;
   public static final RegistryObject<Block> CABLELCC;
   public static final RegistryObject<Block> CABLELT;
   public static final RegistryObject<Block> CABLELTC;
   public static final RegistryObject<Block> CABLEF;
   public static final RegistryObject<Block> CABLET;
   public static final RegistryObject<Block> CABLETC;
   public static final RegistryObject<Block> CABLETX;
   public static final RegistryObject<Block> CABLETXC;
   public static final RegistryObject<Block> CABLETXCC;
   public static final RegistryObject<Block> CABLEX;
   public static final RegistryObject<Block> CABLEXC;
   public static final RegistryObject<Block> STEEL_BATTERY;
   public static final RegistryObject<Block> STEELBATTER_1;
   public static final RegistryObject<Block> STEELBATTER_2;
   public static final RegistryObject<Block> STEELBATTER_3;
   public static final RegistryObject<Block> STEELBATTER_4;
   public static final RegistryObject<Block> STEELSPACESHIP;
   public static final RegistryObject<Block> TITANIUMSPACESHIP;
   public static final RegistryObject<Block> STEEL_SPACESHIPUPRIGHT;
   public static final RegistryObject<Block> TITANIUM_SPACESHIPUPRIGHT;
   public static final RegistryObject<Block> STEELSPACESHIP_2;
   public static final RegistryObject<Block> STEELSPACESHIP_3;
   public static final RegistryObject<Block> STEELSPACESHIP_4;
   public static final RegistryObject<Block> TITANIUMSPACESHIP_2;
   public static final RegistryObject<Block> TITANIUMSPACESHIP_3;
   public static final RegistryObject<Block> TITANIUMSPACESHIP_4;
   public static final RegistryObject<Block> STEELSPACESHIPUPRIGHT_2;
   public static final RegistryObject<Block> STEELSPACESHIPUPRIGHT_3;
   public static final RegistryObject<Block> STEELSPACESHIPUPRIGHT_4;
   public static final RegistryObject<Block> TITANIUMSPACESHIPUPRIGHT_2;
   public static final RegistryObject<Block> TITANIUMSPACESHIPUPRIGHT_3;
   public static final RegistryObject<Block> TITANIUMSPACESHIPUPRIGHT_4;
   public static final RegistryObject<Block> NICKLE_BLOCK;
   public static final RegistryObject<Block> STEEL_BLOCK;
   public static final RegistryObject<Block> NICKLESPACESHIP;
   public static final RegistryObject<Block> NICKLESPACESHIP_2;
   public static final RegistryObject<Block> NICKLESPACESHIP_3;
   public static final RegistryObject<Block> NICKLESPACESHIP_4;
   public static final RegistryObject<Block> NICKLESPACESHIPUPRIGHT;
   public static final RegistryObject<Block> NICKLESPACESHIPUPRIGHT_2;
   public static final RegistryObject<Block> NICKLESPACESHIPUPRIGHT_3;
   public static final RegistryObject<Block> NICKLESPACESHIPUPRIGHT_4;
   public static final RegistryObject<Block> EXTINGUISHED_LANTERN;
   public static final RegistryObject<Block> EXTINGUISHED_LANTERN_HANGING;
   public static final RegistryObject<Block> EXTINGUISHEDTORCH;
   public static final RegistryObject<Block> EXTINGUISHEDTORCHWALL;
   public static final RegistryObject<Block> STONE_CORE_BLOCK;
   public static final RegistryObject<Block> SULPHURIC_ACID;
   public static final RegistryObject<Block> MATIAN_SAND;
   public static final RegistryObject<Block> COMPRESSED_STONE;
   public static final RegistryObject<Block> NITROGEN;
   public static final RegistryObject<Block> ARGON;
   public static final RegistryObject<Block> METHANE;
   public static final RegistryObject<Block> AMMONIA;
   public static final RegistryObject<Block> HYDROGEN;
   public static final RegistryObject<Block> HELIUM;
   public static final RegistryObject<Block> VAPOUR;
   public static final RegistryObject<Block> FLOURINE;
   public static final RegistryObject<Block> BORON;
   public static final RegistryObject<Block> ASHED_SULPHER_STONE;
   public static final RegistryObject<Block> STEEL_RESTONE_RECIEVER_ON;
   public static final RegistryObject<Block> STEEL_RESTONE_RECIEVER_OFF;
   public static final RegistryObject<Block> STEEL_LANDING_PAD_ON;
   public static final RegistryObject<Block> STEEL_LANDING_PAD_OFF;
   public static final RegistryObject<Block> PROJECTOR_TABLE;
   public static final RegistryObject<Block> CHISELED_MARTIAN_STONE;
   public static final RegistryObject<Block> MARTIAN_STONE_TILES;
   public static final RegistryObject<Block> MARTIAN_STONE_BRICKS;
   public static final RegistryObject<Block> POLISHED_MARTIAN_STONE;
   public static final RegistryObject<Block> RAW_NICKEL_STONE;
   public static final RegistryObject<Block> CRUDE_OIL;
   public static final RegistryObject<Block> DETONATOR_TARGET;
   public static final RegistryObject<Block> DETONATOR_TARGET_ON;

   static {
      REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, "cosmos");
      MOON_CLAYDUST = REGISTRY.register("moon_claydust", () -> new MoonClaydustBlock());
      HIGHLY_COMPRESSED_ICE = REGISTRY.register("highly_compressed_ice", () -> new HighlyCompressedIceBlock());
      COMPRESSED_FROZEN_MOON_CLAYDUST = REGISTRY.register("compressed_frozen_moon_claydust", () -> new CompressedFrozenMoonClaydustBlock());
      SULPHURIC_SAND = REGISTRY.register("sulphuric_sand", () -> new SulphuricSandBlock());
      CONCENTRATEDSULPHERORE = REGISTRY.register("concentratedsulpherore", () -> new ConcentratedsulpheroreBlock());
      SULPHER_STONE = REGISTRY.register("sulpher_stone", () -> new SulpherStoneBlock());
      FROZEN_TITANIUMORE = REGISTRY.register("frozen_titaniumore", () -> new FrozenTitaniumoreBlock());
      TITANIUM_BLOCK = REGISTRY.register("titanium_block", () -> new TitaniumBlockBlock());
      SILICONEDMOONCLAY = REGISTRY.register("siliconedmoonclay", () -> new SiliconedmoonclayBlock());
      CHAMBERED_SUPER_SMELTERBLOCK = REGISTRY.register("chambered_super_smelterblock", () -> new ChamberedSuperSmelterblockBlock());
      BRIGHT_FIRE = REGISTRY.register("bright_fire", () -> new BrightFireBlock());
      SULPHER_TNT = REGISTRY.register("sulpher_tnt", () -> new CorrodedSulpherTNTBlock());
      ASHEDSULPHURIC_TNT = REGISTRY.register("ashedsulphuric_tnt", () -> new AshedsulphuricTntBlock());
      HEIGHT_LIMITER = REGISTRY.register("height_limiter", () -> new HeightLimiterBlock());
      LARGESOLARPANEL = REGISTRY.register("largesolarpanel", () -> new LargesolarpanelBlock());
      SMALLSOLARPANEL = REGISTRY.register("smallsolarpanel", () -> new SmallsolarpanelBlock());
      CABLEE = REGISTRY.register("cablee", () -> new CableeBlock());
      CABLE_N = REGISTRY.register("cable_n", () -> new CableNBlock());
      CABLES = REGISTRY.register("cables", () -> new CablesBlock());
      CABLEI = REGISTRY.register("cablei", () -> new CableiBlock());
      CABLEL = REGISTRY.register("cablel", () -> new CablelBlock());
      CABLELC = REGISTRY.register("cablelc", () -> new CablelcBlock());
      CABLELCC = REGISTRY.register("cablelcc", () -> new CablelccBlock());
      CABLELT = REGISTRY.register("cablelt", () -> new CableltBlock());
      CABLELTC = REGISTRY.register("cableltc", () -> new CableltcBlock());
      CABLEF = REGISTRY.register("cablef", () -> new CablefBlock());
      CABLET = REGISTRY.register("cablet", () -> new CabletBlock());
      CABLETC = REGISTRY.register("cabletc", () -> new CabletcBlock());
      CABLETX = REGISTRY.register("cabletx", () -> new CabletxBlock());
      CABLETXC = REGISTRY.register("cabletxc", () -> new CabletxcBlock());
      CABLETXCC = REGISTRY.register("cabletxcc", () -> new CabletxccBlock());
      CABLEX = REGISTRY.register("cablex", () -> new CablexBlock());
      CABLEXC = REGISTRY.register("cablexc", () -> new CablexcBlock());
      STEEL_BATTERY = REGISTRY.register("steel_battery", () -> new SteelBatteryBlock());
      STEELBATTER_1 = REGISTRY.register("steelbatter_1", () -> new Steelbatter1Block());
      STEELBATTER_2 = REGISTRY.register("steelbatter_2", () -> new Steelbatter2Block());
      STEELBATTER_3 = REGISTRY.register("steelbatter_3", () -> new Steelbatter3Block());
      STEELBATTER_4 = REGISTRY.register("steelbatter_4", () -> new Steelbatter4Block());
      STEELSPACESHIP = REGISTRY.register("steelspaceship", () -> new SteelspaceshipBlock());
      TITANIUMSPACESHIP = REGISTRY.register("titaniumspaceship", () -> new TitaniumspaceshipBlock());
      STEEL_SPACESHIPUPRIGHT = REGISTRY.register("steel_spaceshipupright", () -> new SteelSpaceshipuprightBlock());
      TITANIUM_SPACESHIPUPRIGHT = REGISTRY.register("titanium_spaceshipupright", () -> new TitaniumSpaceshipuprightBlock());
      STEELSPACESHIP_2 = REGISTRY.register("steelspaceship_2", () -> new Steelspaceship2Block());
      STEELSPACESHIP_3 = REGISTRY.register("steelspaceship_3", () -> new Steelspaceship3Block());
      STEELSPACESHIP_4 = REGISTRY.register("steelspaceship_4", () -> new Steelspaceship4Block());
      TITANIUMSPACESHIP_2 = REGISTRY.register("titaniumspaceship_2", () -> new Titaniumspaceship2Block());
      TITANIUMSPACESHIP_3 = REGISTRY.register("titaniumspaceship_3", () -> new Titaniumspaceship3Block());
      TITANIUMSPACESHIP_4 = REGISTRY.register("titaniumspaceship_4", () -> new Titaniumspaceship4Block());
      STEELSPACESHIPUPRIGHT_2 = REGISTRY.register("steelspaceshipupright_2", () -> new Steelspaceshipupright2Block());
      STEELSPACESHIPUPRIGHT_3 = REGISTRY.register("steelspaceshipupright_3", () -> new Steelspaceshipupright3Block());
      STEELSPACESHIPUPRIGHT_4 = REGISTRY.register("steelspaceshipupright_4", () -> new Steelspaceshipupright4Block());
      TITANIUMSPACESHIPUPRIGHT_2 = REGISTRY.register("titaniumspaceshipupright_2", () -> new Titaniumspaceshipupright2Block());
      TITANIUMSPACESHIPUPRIGHT_3 = REGISTRY.register("titaniumspaceshipupright_3", () -> new Titaniumspaceshipupright3Block());
      TITANIUMSPACESHIPUPRIGHT_4 = REGISTRY.register("titaniumspaceshipupright_4", () -> new Titaniumspaceshipupright4Block());
      NICKLE_BLOCK = REGISTRY.register("nickle_block", () -> new NickleBlockBlock());
      STEEL_BLOCK = REGISTRY.register("steel_block", () -> new SteelBlockBlock());
      NICKLESPACESHIP = REGISTRY.register("nicklespaceship", () -> new NicklespaceshipBlock());
      NICKLESPACESHIP_2 = REGISTRY.register("nicklespaceship_2", () -> new Nicklespaceship2Block());
      NICKLESPACESHIP_3 = REGISTRY.register("nicklespaceship_3", () -> new Nicklespaceship3Block());
      NICKLESPACESHIP_4 = REGISTRY.register("nicklespaceship_4", () -> new Nicklespaceship4Block());
      NICKLESPACESHIPUPRIGHT = REGISTRY.register("nicklespaceshipupright", () -> new NicklespaceshipuprightBlock());
      NICKLESPACESHIPUPRIGHT_2 = REGISTRY.register("nicklespaceshipupright_2", () -> new Nicklespaceshipupright2Block());
      NICKLESPACESHIPUPRIGHT_3 = REGISTRY.register("nicklespaceshipupright_3", () -> new Nicklespaceshipupright3Block());
      NICKLESPACESHIPUPRIGHT_4 = REGISTRY.register("nicklespaceshipupright_4", () -> new Nicklespaceshipupright4Block());
      EXTINGUISHED_LANTERN = REGISTRY.register("extinguished_lantern", () -> new ExtinguishedLanternBlock());
      EXTINGUISHED_LANTERN_HANGING = REGISTRY.register("extinguished_lantern_hanging", () -> new ExtinguishedLanternHangingBlock());
      EXTINGUISHEDTORCH = REGISTRY.register("extinguishedtorch", () -> new ExtinguishedtorchBlock());
      EXTINGUISHEDTORCHWALL = REGISTRY.register("extinguishedtorchwall", () -> new ExtinguishedtorchwallBlock());
      STONE_CORE_BLOCK = REGISTRY.register("stone_core_block", () -> new StonecoreblockBlock());
      SULPHURIC_ACID = REGISTRY.register("sulphuric_acid", () -> new SulphuricAcidBlock());
      MATIAN_SAND = REGISTRY.register("matian_sand", () -> new MatianSandBlock());
      COMPRESSED_STONE = REGISTRY.register("compressed_stone", () -> new CompressedStoneBlock());
      NITROGEN = REGISTRY.register("nitrogen", () -> new NitrogenBlock());
      ARGON = REGISTRY.register("argon", () -> new ArgonBlock());
      METHANE = REGISTRY.register("methane", () -> new MethaneBlock());
      AMMONIA = REGISTRY.register("ammonia", () -> new AmmoniaBlock());
      HYDROGEN = REGISTRY.register("hydrogen", () -> new HydrogenBlock());
      HELIUM = REGISTRY.register("helium", () -> new HeliumBlock());
      VAPOUR = REGISTRY.register("vapour", () -> new VapourBlock());
      FLOURINE = REGISTRY.register("flourine", () -> new FlourineBlock());
      BORON = REGISTRY.register("boron", () -> new BoronBlock());
      ASHED_SULPHER_STONE = REGISTRY.register("ashed_sulpher_stone", () -> new AshedSulpherStoneBlock());
      STEEL_RESTONE_RECIEVER_ON = REGISTRY.register("steel_restone_reciever_on", () -> new SteelRestoneRecieverONBlock());
      STEEL_RESTONE_RECIEVER_OFF = REGISTRY.register("steel_restone_reciever_off", () -> new SteelRestoneRecieverOFFBlock());
      STEEL_LANDING_PAD_ON = REGISTRY.register("steel_landing_pad_on", () -> new SteelLandingPadONBlock());
      STEEL_LANDING_PAD_OFF = REGISTRY.register("steel_landing_pad_off", () -> new SteelLandingPadOFFBlock());
      PROJECTOR_TABLE = REGISTRY.register("projector_table", () -> new ProjectorTableBlock());
      CHISELED_MARTIAN_STONE = REGISTRY.register("chiseled_martian_stone", () -> new ChiseledMartianStoneBlock());
      MARTIAN_STONE_TILES = REGISTRY.register("martian_stone_tiles", () -> new MartianStoneTilesBlock());
      MARTIAN_STONE_BRICKS = REGISTRY.register("martian_stone_bricks", () -> new MartianStoneBricksBlock());
      POLISHED_MARTIAN_STONE = REGISTRY.register("polished_martian_stone", () -> new PolishedMartianStoneBlock());
      RAW_NICKEL_STONE = REGISTRY.register("raw_nickel_stone", () -> new RawNickelStoneBlock());
      CRUDE_OIL = REGISTRY.register("crude_oil", () -> new CrudeOilBlock());
      DETONATOR_TARGET = REGISTRY.register("detonator_target", () -> new DetonatorTargetBlock());
      DETONATOR_TARGET_ON = REGISTRY.register("detonator_target_on", () -> new DetonatorTargetOnBlock());
   }
}
