package net.lointain.cosmos.init;

import net.lointain.cosmos.item.AshedSulpherDustItem;
import net.lointain.cosmos.item.CrudeOilItem;
import net.lointain.cosmos.item.DeadcompassItem;
import net.lointain.cosmos.item.DetonationControlerItem;
import net.lointain.cosmos.item.DetonationControllerPressedItem;
import net.lointain.cosmos.item.EnergyMeterItem;
import net.lointain.cosmos.item.IronHammerItem;
import net.lointain.cosmos.item.IronPlateItem;
import net.lointain.cosmos.item.LanternextinguishedItem;
import net.lointain.cosmos.item.NickelAxeItem;
import net.lointain.cosmos.item.NickelHoeItem;
import net.lointain.cosmos.item.NickelPickaxeItem;
import net.lointain.cosmos.item.NickelShovelItem;
import net.lointain.cosmos.item.NickelSpaceNoduleItem;
import net.lointain.cosmos.item.NickelSuitItem;
import net.lointain.cosmos.item.NickelSwordItem;
import net.lointain.cosmos.item.NickelarmourItem;
import net.lointain.cosmos.item.NickleIngotItem;
import net.lointain.cosmos.item.NicklePlateItem;
import net.lointain.cosmos.item.RawNickleItem;
import net.lointain.cosmos.item.RawTitaniumItem;
import net.lointain.cosmos.item.RawsiliconItem;
import net.lointain.cosmos.item.SiliconchipItem;
import net.lointain.cosmos.item.SiliconcrystalItem;
import net.lointain.cosmos.item.SpacecompassItem;
import net.lointain.cosmos.item.SteelAxeItem;
import net.lointain.cosmos.item.SteelFlashHelmetOnItem;
import net.lointain.cosmos.item.SteelFueltankItem;
import net.lointain.cosmos.item.SteelHammerItem;
import net.lointain.cosmos.item.SteelHoeItem;
import net.lointain.cosmos.item.SteelIngotItem;
import net.lointain.cosmos.item.SteelNuggetItem;
import net.lointain.cosmos.item.SteelPickaxeItem;
import net.lointain.cosmos.item.SteelPlateItem;
import net.lointain.cosmos.item.SteelShovelItem;
import net.lointain.cosmos.item.SteelSpaceNoduleItem;
import net.lointain.cosmos.item.SteelSuitItem;
import net.lointain.cosmos.item.SteelSwordItem;
import net.lointain.cosmos.item.SteelarmourItem;
import net.lointain.cosmos.item.SteelengineItem;
import net.lointain.cosmos.item.SulpherDustItem;
import net.lointain.cosmos.item.SulphuricAcidItem;
import net.lointain.cosmos.item.SulphuricshardItem;
import net.lointain.cosmos.item.T2ThrusterItem;
import net.lointain.cosmos.item.T3ThrusterItem;
import net.lointain.cosmos.item.T4ThrusterItem;
import net.lointain.cosmos.item.TitaniumAxeItem;
import net.lointain.cosmos.item.TitaniumHoeItem;
import net.lointain.cosmos.item.TitaniumIngotItem;
import net.lointain.cosmos.item.TitaniumPlateItem;
import net.lointain.cosmos.item.TitaniumShowelItem;
import net.lointain.cosmos.item.TitaniumSpaceNoduleItem;
import net.lointain.cosmos.item.TitaniumSuitItem;
import net.lointain.cosmos.item.TitaniumSwordItem;
import net.lointain.cosmos.item.TitaniumarmourItem;
import net.lointain.cosmos.item.TitaniumpickaxeItem;
import net.lointain.cosmos.item.TitaniumspakerItem;
import net.lointain.cosmos.item.TorchextinguishedItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class CosmosModItems {
   public static final DeferredRegister<Item> REGISTRY;
   public static final RegistryObject<Item> MOON_CLAYDUST;
   public static final RegistryObject<Item> HIGHLY_COMPRESSED_ICE;
   public static final RegistryObject<Item> COMPRESSED_FROZEN_MOON_CLAYDUST;
   public static final RegistryObject<Item> SULPHURIC_SAND;
   public static final RegistryObject<Item> CONCENTRATEDSULPHERORE;
   public static final RegistryObject<Item> SULPHER_STONE;
   public static final RegistryObject<Item> RAW_TITANIUM;
   public static final RegistryObject<Item> FROZEN_TITANIUMORE;
   public static final RegistryObject<Item> TITANIUM_INGOT;
   public static final RegistryObject<Item> TITANIUMARMOUR_HELMET;
   public static final RegistryObject<Item> TITANIUMARMOUR_CHESTPLATE;
   public static final RegistryObject<Item> TITANIUMARMOUR_LEGGINGS;
   public static final RegistryObject<Item> TITANIUMARMOUR_BOOTS;
   public static final RegistryObject<Item> TITANIUM_BLOCK;
   public static final RegistryObject<Item> TITANIUM_SWORD;
   public static final RegistryObject<Item> TITANIUM_AXE;
   public static final RegistryObject<Item> TITANIUM_SHOWEL;
   public static final RegistryObject<Item> TITANIUMPICKAXE;
   public static final RegistryObject<Item> TITANIUM_HOE;
   public static final RegistryObject<Item> RAWSILICON;
   public static final RegistryObject<Item> SILICONEDMOONCLAY;
   public static final RegistryObject<Item> SILICONCRYSTAL;
   public static final RegistryObject<Item> CHAMBERED_SUPER_SMELTERBLOCK;
   public static final RegistryObject<Item> SILICONCHIP;
   public static final RegistryObject<Item> SULPHER_DUST;
   public static final RegistryObject<Item> ASHED_SULPHER_DUST;
   public static final RegistryObject<Item> BRIGHT_FIRE;
   public static final RegistryObject<Item> TITANIUMSPAKER;
   public static final RegistryObject<Item> SULPHER_TNT;
   public static final RegistryObject<Item> NICKLE_INGOT;
   public static final RegistryObject<Item> RAW_NICKLE;
   public static final RegistryObject<Item> ASHEDSULPHURIC_TNT;
   public static final RegistryObject<Item> SULPHURICSHARD;
   public static final RegistryObject<Item> HEIGHT_LIMITER;
   public static final RegistryObject<Item> LARGESOLARPANEL;
   public static final RegistryObject<Item> SMALLSOLARPANEL;
   public static final RegistryObject<Item> CABLEE;
   public static final RegistryObject<Item> CABLE_N;
   public static final RegistryObject<Item> CABLES;
   public static final RegistryObject<Item> CABLEI;
   public static final RegistryObject<Item> CABLEL;
   public static final RegistryObject<Item> CABLELC;
   public static final RegistryObject<Item> CABLELCC;
   public static final RegistryObject<Item> CABLELT;
   public static final RegistryObject<Item> CABLELTC;
   public static final RegistryObject<Item> CABLEF;
   public static final RegistryObject<Item> CABLET;
   public static final RegistryObject<Item> CABLETC;
   public static final RegistryObject<Item> CABLETX;
   public static final RegistryObject<Item> CABLETXC;
   public static final RegistryObject<Item> CABLETXCC;
   public static final RegistryObject<Item> CABLEX;
   public static final RegistryObject<Item> CABLEXC;
   public static final RegistryObject<Item> ENERGY_METER;
   public static final RegistryObject<Item> STEEL_BATTERY;
   public static final RegistryObject<Item> STEELBATTER_1;
   public static final RegistryObject<Item> STEELBATTER_2;
   public static final RegistryObject<Item> STEELBATTER_3;
   public static final RegistryObject<Item> STEELBATTER_4;
   public static final RegistryObject<Item> STEELSPACESHIP;
   public static final RegistryObject<Item> TITANIUMSPACESHIP;
   public static final RegistryObject<Item> STEEL_SPACESHIPUPRIGHT;
   public static final RegistryObject<Item> TITANIUM_SPACESHIPUPRIGHT;
   public static final RegistryObject<Item> STEELSPACESHIP_2;
   public static final RegistryObject<Item> STEELSPACESHIP_3;
   public static final RegistryObject<Item> STEELSPACESHIP_4;
   public static final RegistryObject<Item> TITANIUMSPACESHIP_2;
   public static final RegistryObject<Item> TITANIUMSPACESHIP_3;
   public static final RegistryObject<Item> TITANIUMSPACESHIP_4;
   public static final RegistryObject<Item> STEELSPACESHIPUPRIGHT_2;
   public static final RegistryObject<Item> STEELSPACESHIPUPRIGHT_3;
   public static final RegistryObject<Item> STEELSPACESHIPUPRIGHT_4;
   public static final RegistryObject<Item> TITANIUMSPACESHIPUPRIGHT_2;
   public static final RegistryObject<Item> TITANIUMSPACESHIPUPRIGHT_3;
   public static final RegistryObject<Item> TITANIUMSPACESHIPUPRIGHT_4;
   public static final RegistryObject<Item> T_2_THRUSTER;
   public static final RegistryObject<Item> T_3_THRUSTER;
   public static final RegistryObject<Item> T_4_THRUSTER;
   public static final RegistryObject<Item> NICKLE_BLOCK;
   public static final RegistryObject<Item> STEEL_NUGGET;
   public static final RegistryObject<Item> STEEL_INGOT;
   public static final RegistryObject<Item> STEEL_BLOCK;
   public static final RegistryObject<Item> TITANIUM_PLATE;
   public static final RegistryObject<Item> NICKLE_PLATE;
   public static final RegistryObject<Item> STEEL_PLATE;
   public static final RegistryObject<Item> STEELENGINE;
   public static final RegistryObject<Item> STEEL_FUELTANK;
   public static final RegistryObject<Item> NICKLESPACESHIP;
   public static final RegistryObject<Item> NICKLESPACESHIP_2;
   public static final RegistryObject<Item> NICKLESPACESHIP_3;
   public static final RegistryObject<Item> NICKLESPACESHIP_4;
   public static final RegistryObject<Item> NICKLESPACESHIPUPRIGHT;
   public static final RegistryObject<Item> NICKLESPACESHIPUPRIGHT_2;
   public static final RegistryObject<Item> NICKLESPACESHIPUPRIGHT_3;
   public static final RegistryObject<Item> NICKLESPACESHIPUPRIGHT_4;
   public static final RegistryObject<Item> DEADCOMPASS;
   public static final RegistryObject<Item> SPACECOMPASS;
   public static final RegistryObject<Item> EXTINGUISHED_LANTERN;
   public static final RegistryObject<Item> EXTINGUISHED_LANTERN_HANGING;
   public static final RegistryObject<Item> EXTINGUISHEDTORCH;
   public static final RegistryObject<Item> EXTINGUISHEDTORCHWALL;
   public static final RegistryObject<Item> TORCHEXTINGUISHED;
   public static final RegistryObject<Item> LANTERNEXTINGUISHED;
   public static final RegistryObject<Item> STONE_CORE_BLOCK;
   public static final RegistryObject<Item> SULPHURIC_ACID_BUCKET;
   public static final RegistryObject<Item> MATIAN_SAND;
   public static final RegistryObject<Item> COMPRESSED_STONE;
   public static final RegistryObject<Item> STEEL_SUIT_HELMET;
   public static final RegistryObject<Item> STEEL_SUIT_CHESTPLATE;
   public static final RegistryObject<Item> STEEL_SUIT_LEGGINGS;
   public static final RegistryObject<Item> STEEL_SUIT_BOOTS;
   public static final RegistryObject<Item> NITROGEN;
   public static final RegistryObject<Item> ARGON;
   public static final RegistryObject<Item> METHANE;
   public static final RegistryObject<Item> AMMONIA;
   public static final RegistryObject<Item> HYDROGEN;
   public static final RegistryObject<Item> HELIUM;
   public static final RegistryObject<Item> VAPOUR;
   public static final RegistryObject<Item> FLOURINE;
   public static final RegistryObject<Item> BORON;
   public static final RegistryObject<Item> TITANIUM_SUIT_HELMET;
   public static final RegistryObject<Item> TITANIUM_SUIT_CHESTPLATE;
   public static final RegistryObject<Item> TITANIUM_SUIT_LEGGINGS;
   public static final RegistryObject<Item> TITANIUM_SUIT_BOOTS;
   public static final RegistryObject<Item> NICKEL_SUIT_HELMET;
   public static final RegistryObject<Item> NICKEL_SUIT_CHESTPLATE;
   public static final RegistryObject<Item> NICKEL_SUIT_LEGGINGS;
   public static final RegistryObject<Item> NICKEL_SUIT_BOOTS;
   public static final RegistryObject<Item> ASHED_SULPHER_STONE;
   public static final RegistryObject<Item> STEEL_SPACE_NODULE;
   public static final RegistryObject<Item> TITANIUM_SPACE_NODULE;
   public static final RegistryObject<Item> NICKEL_SPACE_NODULE;
   public static final RegistryObject<Item> STEEL_SWORD;
   public static final RegistryObject<Item> STEEL_AXE;
   public static final RegistryObject<Item> STEEL_SHOVEL;
   public static final RegistryObject<Item> STEEL_PICKAXE;
   public static final RegistryObject<Item> STEEL_HOE;
   public static final RegistryObject<Item> NICKEL_SWORD;
   public static final RegistryObject<Item> NICKEL_AXE;
   public static final RegistryObject<Item> NICKEL_SHOVEL;
   public static final RegistryObject<Item> NICKEL_PICKAXE;
   public static final RegistryObject<Item> NICKEL_HOE;
   public static final RegistryObject<Item> STEELARMOUR_HELMET;
   public static final RegistryObject<Item> STEELARMOUR_CHESTPLATE;
   public static final RegistryObject<Item> STEELARMOUR_LEGGINGS;
   public static final RegistryObject<Item> STEELARMOUR_BOOTS;
   public static final RegistryObject<Item> NICKELARMOUR_HELMET;
   public static final RegistryObject<Item> NICKELARMOUR_CHESTPLATE;
   public static final RegistryObject<Item> NICKELARMOUR_LEGGINGS;
   public static final RegistryObject<Item> NICKELARMOUR_BOOTS;
   public static final RegistryObject<Item> IRON_PLATE;
   public static final RegistryObject<Item> IRON_HAMMER;
   public static final RegistryObject<Item> STEEL_HAMMER;
   public static final RegistryObject<Item> STEEL_RESTONE_RECIEVER_ON;
   public static final RegistryObject<Item> STEEL_RESTONE_RECIEVER_OFF;
   public static final RegistryObject<Item> STEEL_LANDING_PAD_ON;
   public static final RegistryObject<Item> STEEL_LANDING_PAD_OFF;
   public static final RegistryObject<Item> PROJECTOR_TABLE;
   public static final RegistryObject<Item> CHISELED_MARTIAN_STONE;
   public static final RegistryObject<Item> MARTIAN_STONE_TILES;
   public static final RegistryObject<Item> MARTIAN_STONE_BRICKS;
   public static final RegistryObject<Item> POLISHED_MARTIAN_STONE;
   public static final RegistryObject<Item> RAW_NICKEL_STONE;
   public static final RegistryObject<Item> STEEL_ROVER_SPAWN_EGG;
   public static final RegistryObject<Item> TITANIUM_ROVER_SPAWN_EGG;
   public static final RegistryObject<Item> NICKEL_ROVER_SPAWN_EGG;
   public static final RegistryObject<Item> CRUDE_OIL_BUCKET;
   public static final RegistryObject<Item> DETONATION_CONTROLER;
   public static final RegistryObject<Item> DETONATOR_TARGET;
   public static final RegistryObject<Item> DETONATOR_TARGET_ON;
   public static final RegistryObject<Item> DETONATION_CONTROLLER_PRESSED;
   public static final RegistryObject<Item> STEEL_FLASH_HELMET_ON_HELMET;

   private static RegistryObject<Item> block(RegistryObject<Block> block) {
      return REGISTRY.register(block.getId().m_135815_(), () -> new BlockItem((Block)block.get(), new Item.Properties()));
   }

   static {
      REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, "cosmos");
      MOON_CLAYDUST = block(CosmosModBlocks.MOON_CLAYDUST);
      HIGHLY_COMPRESSED_ICE = block(CosmosModBlocks.HIGHLY_COMPRESSED_ICE);
      COMPRESSED_FROZEN_MOON_CLAYDUST = block(CosmosModBlocks.COMPRESSED_FROZEN_MOON_CLAYDUST);
      SULPHURIC_SAND = block(CosmosModBlocks.SULPHURIC_SAND);
      CONCENTRATEDSULPHERORE = block(CosmosModBlocks.CONCENTRATEDSULPHERORE);
      SULPHER_STONE = block(CosmosModBlocks.SULPHER_STONE);
      RAW_TITANIUM = REGISTRY.register("raw_titanium", () -> new RawTitaniumItem());
      FROZEN_TITANIUMORE = block(CosmosModBlocks.FROZEN_TITANIUMORE);
      TITANIUM_INGOT = REGISTRY.register("titanium_ingot", () -> new TitaniumIngotItem());
      TITANIUMARMOUR_HELMET = REGISTRY.register("titaniumarmour_helmet", () -> new TitaniumarmourItem.Helmet());
      TITANIUMARMOUR_CHESTPLATE = REGISTRY.register("titaniumarmour_chestplate", () -> new TitaniumarmourItem.Chestplate());
      TITANIUMARMOUR_LEGGINGS = REGISTRY.register("titaniumarmour_leggings", () -> new TitaniumarmourItem.Leggings());
      TITANIUMARMOUR_BOOTS = REGISTRY.register("titaniumarmour_boots", () -> new TitaniumarmourItem.Boots());
      TITANIUM_BLOCK = block(CosmosModBlocks.TITANIUM_BLOCK);
      TITANIUM_SWORD = REGISTRY.register("titanium_sword", () -> new TitaniumSwordItem());
      TITANIUM_AXE = REGISTRY.register("titanium_axe", () -> new TitaniumAxeItem());
      TITANIUM_SHOWEL = REGISTRY.register("titanium_showel", () -> new TitaniumShowelItem());
      TITANIUMPICKAXE = REGISTRY.register("titaniumpickaxe", () -> new TitaniumpickaxeItem());
      TITANIUM_HOE = REGISTRY.register("titanium_hoe", () -> new TitaniumHoeItem());
      RAWSILICON = REGISTRY.register("rawsilicon", () -> new RawsiliconItem());
      SILICONEDMOONCLAY = block(CosmosModBlocks.SILICONEDMOONCLAY);
      SILICONCRYSTAL = REGISTRY.register("siliconcrystal", () -> new SiliconcrystalItem());
      CHAMBERED_SUPER_SMELTERBLOCK = block(CosmosModBlocks.CHAMBERED_SUPER_SMELTERBLOCK);
      SILICONCHIP = REGISTRY.register("siliconchip", () -> new SiliconchipItem());
      SULPHER_DUST = REGISTRY.register("sulpher_dust", () -> new SulpherDustItem());
      ASHED_SULPHER_DUST = REGISTRY.register("ashed_sulpher_dust", () -> new AshedSulpherDustItem());
      BRIGHT_FIRE = block(CosmosModBlocks.BRIGHT_FIRE);
      TITANIUMSPAKER = REGISTRY.register("titaniumspaker", () -> new TitaniumspakerItem());
      SULPHER_TNT = block(CosmosModBlocks.SULPHER_TNT);
      NICKLE_INGOT = REGISTRY.register("nickle_ingot", () -> new NickleIngotItem());
      RAW_NICKLE = REGISTRY.register("raw_nickle", () -> new RawNickleItem());
      ASHEDSULPHURIC_TNT = block(CosmosModBlocks.ASHEDSULPHURIC_TNT);
      SULPHURICSHARD = REGISTRY.register("sulphuricshard", () -> new SulphuricshardItem());
      HEIGHT_LIMITER = block(CosmosModBlocks.HEIGHT_LIMITER);
      LARGESOLARPANEL = block(CosmosModBlocks.LARGESOLARPANEL);
      SMALLSOLARPANEL = block(CosmosModBlocks.SMALLSOLARPANEL);
      CABLEE = block(CosmosModBlocks.CABLEE);
      CABLE_N = block(CosmosModBlocks.CABLE_N);
      CABLES = block(CosmosModBlocks.CABLES);
      CABLEI = block(CosmosModBlocks.CABLEI);
      CABLEL = block(CosmosModBlocks.CABLEL);
      CABLELC = block(CosmosModBlocks.CABLELC);
      CABLELCC = block(CosmosModBlocks.CABLELCC);
      CABLELT = block(CosmosModBlocks.CABLELT);
      CABLELTC = block(CosmosModBlocks.CABLELTC);
      CABLEF = block(CosmosModBlocks.CABLEF);
      CABLET = block(CosmosModBlocks.CABLET);
      CABLETC = block(CosmosModBlocks.CABLETC);
      CABLETX = block(CosmosModBlocks.CABLETX);
      CABLETXC = block(CosmosModBlocks.CABLETXC);
      CABLETXCC = block(CosmosModBlocks.CABLETXCC);
      CABLEX = block(CosmosModBlocks.CABLEX);
      CABLEXC = block(CosmosModBlocks.CABLEXC);
      ENERGY_METER = REGISTRY.register("energy_meter", () -> new EnergyMeterItem());
      STEEL_BATTERY = block(CosmosModBlocks.STEEL_BATTERY);
      STEELBATTER_1 = block(CosmosModBlocks.STEELBATTER_1);
      STEELBATTER_2 = block(CosmosModBlocks.STEELBATTER_2);
      STEELBATTER_3 = block(CosmosModBlocks.STEELBATTER_3);
      STEELBATTER_4 = block(CosmosModBlocks.STEELBATTER_4);
      STEELSPACESHIP = block(CosmosModBlocks.STEELSPACESHIP);
      TITANIUMSPACESHIP = block(CosmosModBlocks.TITANIUMSPACESHIP);
      STEEL_SPACESHIPUPRIGHT = block(CosmosModBlocks.STEEL_SPACESHIPUPRIGHT);
      TITANIUM_SPACESHIPUPRIGHT = block(CosmosModBlocks.TITANIUM_SPACESHIPUPRIGHT);
      STEELSPACESHIP_2 = block(CosmosModBlocks.STEELSPACESHIP_2);
      STEELSPACESHIP_3 = block(CosmosModBlocks.STEELSPACESHIP_3);
      STEELSPACESHIP_4 = block(CosmosModBlocks.STEELSPACESHIP_4);
      TITANIUMSPACESHIP_2 = block(CosmosModBlocks.TITANIUMSPACESHIP_2);
      TITANIUMSPACESHIP_3 = block(CosmosModBlocks.TITANIUMSPACESHIP_3);
      TITANIUMSPACESHIP_4 = block(CosmosModBlocks.TITANIUMSPACESHIP_4);
      STEELSPACESHIPUPRIGHT_2 = block(CosmosModBlocks.STEELSPACESHIPUPRIGHT_2);
      STEELSPACESHIPUPRIGHT_3 = block(CosmosModBlocks.STEELSPACESHIPUPRIGHT_3);
      STEELSPACESHIPUPRIGHT_4 = block(CosmosModBlocks.STEELSPACESHIPUPRIGHT_4);
      TITANIUMSPACESHIPUPRIGHT_2 = block(CosmosModBlocks.TITANIUMSPACESHIPUPRIGHT_2);
      TITANIUMSPACESHIPUPRIGHT_3 = block(CosmosModBlocks.TITANIUMSPACESHIPUPRIGHT_3);
      TITANIUMSPACESHIPUPRIGHT_4 = block(CosmosModBlocks.TITANIUMSPACESHIPUPRIGHT_4);
      T_2_THRUSTER = REGISTRY.register("t_2_thruster", () -> new T2ThrusterItem());
      T_3_THRUSTER = REGISTRY.register("t_3_thruster", () -> new T3ThrusterItem());
      T_4_THRUSTER = REGISTRY.register("t_4_thruster", () -> new T4ThrusterItem());
      NICKLE_BLOCK = block(CosmosModBlocks.NICKLE_BLOCK);
      STEEL_NUGGET = REGISTRY.register("steel_nugget", () -> new SteelNuggetItem());
      STEEL_INGOT = REGISTRY.register("steel_ingot", () -> new SteelIngotItem());
      STEEL_BLOCK = block(CosmosModBlocks.STEEL_BLOCK);
      TITANIUM_PLATE = REGISTRY.register("titanium_plate", () -> new TitaniumPlateItem());
      NICKLE_PLATE = REGISTRY.register("nickle_plate", () -> new NicklePlateItem());
      STEEL_PLATE = REGISTRY.register("steel_plate", () -> new SteelPlateItem());
      STEELENGINE = REGISTRY.register("steelengine", () -> new SteelengineItem());
      STEEL_FUELTANK = REGISTRY.register("steel_fueltank", () -> new SteelFueltankItem());
      NICKLESPACESHIP = block(CosmosModBlocks.NICKLESPACESHIP);
      NICKLESPACESHIP_2 = block(CosmosModBlocks.NICKLESPACESHIP_2);
      NICKLESPACESHIP_3 = block(CosmosModBlocks.NICKLESPACESHIP_3);
      NICKLESPACESHIP_4 = block(CosmosModBlocks.NICKLESPACESHIP_4);
      NICKLESPACESHIPUPRIGHT = block(CosmosModBlocks.NICKLESPACESHIPUPRIGHT);
      NICKLESPACESHIPUPRIGHT_2 = block(CosmosModBlocks.NICKLESPACESHIPUPRIGHT_2);
      NICKLESPACESHIPUPRIGHT_3 = block(CosmosModBlocks.NICKLESPACESHIPUPRIGHT_3);
      NICKLESPACESHIPUPRIGHT_4 = block(CosmosModBlocks.NICKLESPACESHIPUPRIGHT_4);
      DEADCOMPASS = REGISTRY.register("deadcompass", () -> new DeadcompassItem());
      SPACECOMPASS = REGISTRY.register("spacecompass", () -> new SpacecompassItem());
      EXTINGUISHED_LANTERN = block(CosmosModBlocks.EXTINGUISHED_LANTERN);
      EXTINGUISHED_LANTERN_HANGING = block(CosmosModBlocks.EXTINGUISHED_LANTERN_HANGING);
      EXTINGUISHEDTORCH = block(CosmosModBlocks.EXTINGUISHEDTORCH);
      EXTINGUISHEDTORCHWALL = block(CosmosModBlocks.EXTINGUISHEDTORCHWALL);
      TORCHEXTINGUISHED = REGISTRY.register("torchextinguished", () -> new TorchextinguishedItem());
      LANTERNEXTINGUISHED = REGISTRY.register("lanternextinguished", () -> new LanternextinguishedItem());
      STONE_CORE_BLOCK = block(CosmosModBlocks.STONE_CORE_BLOCK);
      SULPHURIC_ACID_BUCKET = REGISTRY.register("sulphuric_acid_bucket", () -> new SulphuricAcidItem());
      MATIAN_SAND = block(CosmosModBlocks.MATIAN_SAND);
      COMPRESSED_STONE = block(CosmosModBlocks.COMPRESSED_STONE);
      STEEL_SUIT_HELMET = REGISTRY.register("steel_suit_helmet", () -> new SteelSuitItem.Helmet());
      STEEL_SUIT_CHESTPLATE = REGISTRY.register("steel_suit_chestplate", () -> new SteelSuitItem.Chestplate());
      STEEL_SUIT_LEGGINGS = REGISTRY.register("steel_suit_leggings", () -> new SteelSuitItem.Leggings());
      STEEL_SUIT_BOOTS = REGISTRY.register("steel_suit_boots", () -> new SteelSuitItem.Boots());
      NITROGEN = block(CosmosModBlocks.NITROGEN);
      ARGON = block(CosmosModBlocks.ARGON);
      METHANE = block(CosmosModBlocks.METHANE);
      AMMONIA = block(CosmosModBlocks.AMMONIA);
      HYDROGEN = block(CosmosModBlocks.HYDROGEN);
      HELIUM = block(CosmosModBlocks.HELIUM);
      VAPOUR = block(CosmosModBlocks.VAPOUR);
      FLOURINE = block(CosmosModBlocks.FLOURINE);
      BORON = block(CosmosModBlocks.BORON);
      TITANIUM_SUIT_HELMET = REGISTRY.register("titanium_suit_helmet", () -> new TitaniumSuitItem.Helmet());
      TITANIUM_SUIT_CHESTPLATE = REGISTRY.register("titanium_suit_chestplate", () -> new TitaniumSuitItem.Chestplate());
      TITANIUM_SUIT_LEGGINGS = REGISTRY.register("titanium_suit_leggings", () -> new TitaniumSuitItem.Leggings());
      TITANIUM_SUIT_BOOTS = REGISTRY.register("titanium_suit_boots", () -> new TitaniumSuitItem.Boots());
      NICKEL_SUIT_HELMET = REGISTRY.register("nickel_suit_helmet", () -> new NickelSuitItem.Helmet());
      NICKEL_SUIT_CHESTPLATE = REGISTRY.register("nickel_suit_chestplate", () -> new NickelSuitItem.Chestplate());
      NICKEL_SUIT_LEGGINGS = REGISTRY.register("nickel_suit_leggings", () -> new NickelSuitItem.Leggings());
      NICKEL_SUIT_BOOTS = REGISTRY.register("nickel_suit_boots", () -> new NickelSuitItem.Boots());
      ASHED_SULPHER_STONE = block(CosmosModBlocks.ASHED_SULPHER_STONE);
      STEEL_SPACE_NODULE = REGISTRY.register("steel_space_nodule", () -> new SteelSpaceNoduleItem());
      TITANIUM_SPACE_NODULE = REGISTRY.register("titanium_space_nodule", () -> new TitaniumSpaceNoduleItem());
      NICKEL_SPACE_NODULE = REGISTRY.register("nickel_space_nodule", () -> new NickelSpaceNoduleItem());
      STEEL_SWORD = REGISTRY.register("steel_sword", () -> new SteelSwordItem());
      STEEL_AXE = REGISTRY.register("steel_axe", () -> new SteelAxeItem());
      STEEL_SHOVEL = REGISTRY.register("steel_shovel", () -> new SteelShovelItem());
      STEEL_PICKAXE = REGISTRY.register("steel_pickaxe", () -> new SteelPickaxeItem());
      STEEL_HOE = REGISTRY.register("steel_hoe", () -> new SteelHoeItem());
      NICKEL_SWORD = REGISTRY.register("nickel_sword", () -> new NickelSwordItem());
      NICKEL_AXE = REGISTRY.register("nickel_axe", () -> new NickelAxeItem());
      NICKEL_SHOVEL = REGISTRY.register("nickel_shovel", () -> new NickelShovelItem());
      NICKEL_PICKAXE = REGISTRY.register("nickel_pickaxe", () -> new NickelPickaxeItem());
      NICKEL_HOE = REGISTRY.register("nickel_hoe", () -> new NickelHoeItem());
      STEELARMOUR_HELMET = REGISTRY.register("steelarmour_helmet", () -> new SteelarmourItem.Helmet());
      STEELARMOUR_CHESTPLATE = REGISTRY.register("steelarmour_chestplate", () -> new SteelarmourItem.Chestplate());
      STEELARMOUR_LEGGINGS = REGISTRY.register("steelarmour_leggings", () -> new SteelarmourItem.Leggings());
      STEELARMOUR_BOOTS = REGISTRY.register("steelarmour_boots", () -> new SteelarmourItem.Boots());
      NICKELARMOUR_HELMET = REGISTRY.register("nickelarmour_helmet", () -> new NickelarmourItem.Helmet());
      NICKELARMOUR_CHESTPLATE = REGISTRY.register("nickelarmour_chestplate", () -> new NickelarmourItem.Chestplate());
      NICKELARMOUR_LEGGINGS = REGISTRY.register("nickelarmour_leggings", () -> new NickelarmourItem.Leggings());
      NICKELARMOUR_BOOTS = REGISTRY.register("nickelarmour_boots", () -> new NickelarmourItem.Boots());
      IRON_PLATE = REGISTRY.register("iron_plate", () -> new IronPlateItem());
      IRON_HAMMER = REGISTRY.register("iron_hammer", () -> new IronHammerItem());
      STEEL_HAMMER = REGISTRY.register("steel_hammer", () -> new SteelHammerItem());
      STEEL_RESTONE_RECIEVER_ON = block(CosmosModBlocks.STEEL_RESTONE_RECIEVER_ON);
      STEEL_RESTONE_RECIEVER_OFF = block(CosmosModBlocks.STEEL_RESTONE_RECIEVER_OFF);
      STEEL_LANDING_PAD_ON = block(CosmosModBlocks.STEEL_LANDING_PAD_ON);
      STEEL_LANDING_PAD_OFF = block(CosmosModBlocks.STEEL_LANDING_PAD_OFF);
      PROJECTOR_TABLE = block(CosmosModBlocks.PROJECTOR_TABLE);
      CHISELED_MARTIAN_STONE = block(CosmosModBlocks.CHISELED_MARTIAN_STONE);
      MARTIAN_STONE_TILES = block(CosmosModBlocks.MARTIAN_STONE_TILES);
      MARTIAN_STONE_BRICKS = block(CosmosModBlocks.MARTIAN_STONE_BRICKS);
      POLISHED_MARTIAN_STONE = block(CosmosModBlocks.POLISHED_MARTIAN_STONE);
      RAW_NICKEL_STONE = block(CosmosModBlocks.RAW_NICKEL_STONE);
      STEEL_ROVER_SPAWN_EGG = REGISTRY.register("steel_rover_spawn_egg", () -> new ForgeSpawnEggItem(CosmosModEntities.STEEL_ROVER, -6750208, -13421773, new Item.Properties()));
      TITANIUM_ROVER_SPAWN_EGG = REGISTRY.register("titanium_rover_spawn_egg", () -> new ForgeSpawnEggItem(CosmosModEntities.TITANIUM_ROVER, -16737844, -13421773, new Item.Properties()));
      NICKEL_ROVER_SPAWN_EGG = REGISTRY.register("nickel_rover_spawn_egg", () -> new ForgeSpawnEggItem(CosmosModEntities.NICKEL_ROVER, -16751053, -10066330, new Item.Properties()));
      CRUDE_OIL_BUCKET = REGISTRY.register("crude_oil_bucket", () -> new CrudeOilItem());
      DETONATION_CONTROLER = REGISTRY.register("detonation_controler", () -> new DetonationControlerItem());
      DETONATOR_TARGET = block(CosmosModBlocks.DETONATOR_TARGET);
      DETONATOR_TARGET_ON = block(CosmosModBlocks.DETONATOR_TARGET_ON);
      DETONATION_CONTROLLER_PRESSED = REGISTRY.register("detonation_controller_pressed", () -> new DetonationControllerPressedItem());
      STEEL_FLASH_HELMET_ON_HELMET = REGISTRY.register("steel_flash_helmet_on_helmet", () -> new SteelFlashHelmetOnItem.Helmet());
   }
}
